### PR TITLE
Update my website portofolio for assignment task

### PR DESCRIPTION
**Pull request by fhanyuh**
Early PR avoid conflict with other academician, but its still using tailwind, next i'll update into pure vanilla css and some styling

### CODE REVIEW

**Comment by fakhrip** [comment]
Hello @Alizaaaja4 , before i can even review this, can you tell us here for what is the bare minimum process of the website until the mentors could actually review the PR (along with the website)?

**Comment by fakhrip** [comment]
Or should the process of reviewing the PR and reviewing the website be two different decoupled stuff?

**Comment by Alizaaaja4** [comment]
> Hello @Alizaaaja4 , before i can even review this, can you tell us here for what is the bare minimum process of the website until the mentors could actually review the PR (along with the website)?

Sorry for the delay in replying. So, the requirement is to have completed all parts of the portfolio website, including About Me, Portfolio, and Contact Information, and make sure the website has been deployed to Vercel, Netlify, or GitHub Pages.

**Comment by Alizaaaja4** [comment]
> Or should the process of reviewing the PR and reviewing the website be two different decoupled stuff?

That's right, the review process should be separated. PR reviews are done separately, while website reviews are done during presentation sessions.

**Comment by fakhrip** [comment]
> > Or should the process of reviewing the PR and reviewing the website be two different decoupled stuff?
> 
> That's right, the review process should be separated. PR reviews are done separately, while website reviews are done during presentation sessions.

I see, sure thanks for the clarification!

**Review by fakhrip — APPROVED** [review]
Cool, im not sure if the url is what you intend to have, otherwise the rest are good enough, keep it up!

**Comment by fakhrip** [comment]
> Cool, im not sure if the url is what you intend to have, otherwise the rest are good enough, keep it up!

just remember this for next time @fhanyuh that you dont want to write the PR title that way, you would have to make it clearer by stating whose website that you are trying to add, please dont just say "my website" as people wont directly understand who is "my" in this case

so its better to be written as "Update fhanyuh website portfolio" for example 👍

**Pull request merged**
