### PR TITLE
feat: Add NUE's portfolio into the README.md.

### PR DESCRIPTION
**Pull request by EintsWaveX**
Hi to all tentors and mentors, here I would like to add my brand-new portfolio into the Academy's README.md file. With all the pleasure been given, I'd like to thank for the behalf on the PR here... Thank you once again ☆*: .｡. o(≧▽≦)o .｡.:*☆

### CODE REVIEW

**Review by fakhrip — CHANGES_REQUESTED** [review]
Hello @EintsWaveX , you have to fix this first so that the website link is on a new line, thanks!

**Comment by EintsWaveX** [comment]
Hi @fakhrip, thanks for the suggestion to re-add it back onto the next line... I've updated it nonetheless, also renaming the file name back to all uppercase.

**Review by fakhrip — APPROVED** [review]
image

I dont think you renamed it(?) but anyway its already good to go now, good job!

**Comment by EintsWaveX** [comment]
Hmmm, I think it doesn't affect the real file on the main repo though, since I changed it locally (prob?), maybe I'll find it later on how to do so, since it feels weird seeing the README only being capitalized once for some reason hehehe...

**Pull request merged**
