### PR TITLE
Update zaidanah website portfolio for assignment task

### PR DESCRIPTION
**Pull request by zaidanah**
Adding my personal website link to the Readme.md

### CODE REVIEW

**Comment by fakhrip** [comment]
Hi @zaidanah, please update the PR title following my suggestion for fhanyuh here https://github.com/Daskom-Lab/2024-Academy/pull/56#issuecomment-2295113773, also please dont use all-caps like that, the PR title are meant to be a commit title later when merging, so think about writing PR title as in writing commit title, these 2 are pretty much the same thing

Please tag me here again after you changed it as i might not get the notifications, then i will review your PR again

**Comment by zaidanah** [comment]
> Hi @zaidanah, please update the PR title following my suggestion for fhanyuh here [#56 (comment)](https://github.com/Daskom-Lab/2024-Academy/pull/56#issuecomment-2295113773), also please dont use all-caps like that, the PR title are meant to be a commit title later when merging, so think about writing PR title as in writing commit title, these 2 are pretty much the same thing
> 
> Please tag me here again after you changed it as i might not get the notifications, then i will review your PR again

> Done

**Comment by fakhrip** [comment]
> > Hi @zaidanah, please update the PR title following my suggestion for fhanyuh here [#56 (comment)](https://github.com/Daskom-Lab/2024-Academy/pull/56#issuecomment-2295113773), also please dont use all-caps like that, the PR title are meant to be a commit title later when merging, so think about writing PR title as in writing commit title, these 2 are pretty much the same thing
> > Please tag me here again after you changed it as i might not get the notifications, then i will review your PR again
> 
> > Done @fakhrip, My apologies for the oversight.

i think you just made another oversight 😆 , please read my suggestion carefully

**Comment by zaidanah** [comment]
> > > Hi @zaidanah, please update the PR title following my suggestion for fhanyuh here [#56 (comment)](https://github.com/Daskom-Lab/2024-Academy/pull/56#issuecomment-2295113773), also please dont use all-caps like that, the PR title are meant to be a commit title later when merging, so think about writing PR title as in writing commit title, these 2 are pretty much the same thing
> > > Please tag me here again after you changed it as i might not get the notifications, then i will review your PR again
> > 
> > 
> > > Done @fakhrip, My apologies for the oversight.
> 
> i think you just made another oversight 😆 , please read my suggestion carefully

Oops, missed that! I’ve updated the PR title following your suggestion. Thanks for pointing it out.

**Review by fakhrip — APPROVED** [review]
Sure, no problem, thats good, keep it up!

**Pull request merged**
