### PR TITLE
chore: add Muhammad Hafiz as 2024 Academician

### PR DESCRIPTION
**Pull request by mhafiz03**
I just followed las instruciones [aqui](https://github.com/mhafiz03/2024-Academy/blob/main/resources/git_and_github/010_pull_request.md) (tambahin nama ku di readme dan bikin 1 commit), por favor ayudame en este review. LGTM? (Looks Green To Me)

### CODE REVIEW

**Comment by Alizaaaja4** [comment]
Revision:
1. Pay attention to the picture below. It should be noted that there are some details that are not meticulous in this section. Kindly repair and ensure all elements are checked carefully 
WhatsApp Image 2024-08-09 at 13 35 10_f54586ee

**Review by fakhrip — DISMISSED** [review]
I dont think i have to say congrats since this is not your first PR, no? 🤣 
and since you might already understand the convention of a PR and stuff, you should have probably know that there shouldnt be any `.` in a PR title, please remove it later on 👍

**Comment by mhafiz03** [comment]
Done, again

**Comment by fakhrip** [comment]
oh and on another note, please never do any force push unless you are in a special situation that force you to do so, otherwise other people that might be working in the same branch as you are in can lose their commits 👍

**Comment by mhafiz03** [comment]
> I dont think i have to say congrats since this is not your first PR, no? 🤣 and since you might already understand the convention of a PR and stuff, you should have probably know that there shouldnt be any `.` in a PR title, please remove it later on 👍

thank you, my first PR was actually [this one](https://github.com/dmMaze/BallonsTranslator/pull/200) lol

**Review by fakhrip — APPROVED** [review]

**Comment by fakhrip** [comment]
> > I dont think i have to say congrats since this is not your first PR, no? 🤣 and since you might already understand the convention of a PR and stuff, you should have probably know that there shouldnt be any `.` in a PR title, please remove it later on 👍
> 
> thank you, my first PR was actually [this one](https://github.com/dmMaze/BallonsTranslator/pull/200) lol

yeah, knew it XD, thats cool 👍

**Comment by fakhrip** [comment]
> > I dont think i have to say congrats since this is not your first PR, no? 🤣 and since you might already understand the convention of a PR and stuff, you should have probably know that there shouldnt be any `.` in a PR title, please remove it later on 👍
> 
> thank you, my first PR was actually [this one](https://github.com/dmMaze/BallonsTranslator/pull/92) lol
> 
> edit: wrong pr

since this is a public repo, you might want to remove the link btw, unless you actually do want it to be seen by everyone on that repo 🤣 
image

**Comment by mhafiz03** [comment]
I

> > > I dont think i have to say congrats since this is not your first PR, no? 🤣 and since you might already understand the convention of a PR and stuff, you should have probably know that there shouldnt be any `.` in a PR title, please remove it later on 👍
> > 
> > 
> > thank you, my first PR was actually [this one](https://github.com/dmMaze/BallonsTranslator/pull/92) lol
> > edit: wrong pr
> 
> since this is a public repo, you might want to remove the link btw, unless you actually do want it to be seen by everyone on that repo 🤣 

Even if I edit it, the mention is still there :skull:, oh man I'm doxxing myself

**Pull request merged**
